### ISSUE TITLE
possibility to add automatic search for every slot?

### ISSUE THREAD

**Issue by pettrs** [adamgiles1/bank-equipment-stat-filter#1]
currently, you have to choose between all options 
![image](https://github.com/adamgiles1/bank-equipment-stat-filter/assets/75093127/1d1daec0-aefe-468e-b35a-c235dc9c2f84)
is it possible to show it for all slots simultaneously? maybe, you want to also put it in a gear orientation similar to what the equipment inspector looks like? would make it a lot more user-friendly.

![image](https://github.com/adamgiles1/bank-equipment-stat-filter/assets/75093127/3d5f6883-bba0-4a2d-927c-120314f58712)

**Comment by jkryspin** [comment]
Resolved by #2 
@adamgiles1 can you take a peek? I know this repo is a bit old but this plugin is super valuable for ironman

**Comment by adamgiles1** [comment]
@jkryspin Oh nice! I had been meaning to get around to this feature, but never did. I'll try to look over your commit this weekend, thanks!

**Comment by adamgiles1** [comment]
The changes have been merged by runelite, and the feature is now in the pluginhub. Thanks to @jkryspin, I will mark this as resolved
